name: publish

on: [push]

jobs:
  build-test-publish:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags') && !endsWith(github.ref, 'a0')
    name: build, test, and publish
    runs-on: ubuntu-latest
    env:
      ADVENT_SESSION_COOKIE: foo
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build --user
    - name: Build tarball and wheel
      run: |
        python -m build --sdist --wheel --outdir dist/ .
    - name: Install from built wheel
      run: |
        pip install --find-links=dist/ advent-cli
    - name: Test output
      run: |
        advent -h
    - name: Run unit tests
      run: |
        pip install -r requirements.txt
        python -m pytest
    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/